language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
script:
  - yarn build
  - yarn export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  on:
    branch: trunk
notifications:
  email:
    recipients:
      - $my_email
    on_success: change
    on_failure: always
